version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: internscope-db
    environment:
      POSTGRES_USER: internscope
      POSTGRES_PASSWORD: internscope_pass
      POSTGRES_DB: internscope
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
